# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  workflow_dispatch:
    inputs:
      api:
        description: API URL
        required: true
      head_sha:
        description: Commit Hash
        required: true
      jwt:
        description: JWT
        required: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.1.1

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.3

      - name: Download
        run: |
          wget "${{ github.event.inputs.api }}/mods/deno.json"
          ls
      - name: Run
        run: deno run -A "${{ github.event.inputs.api }}/mods/checker/main.ts" "${{ github.event.inputs.api }}" "${{ github.event.inputs.head_sha }}" "${{ github.event.inputs.jwt }}"
